### PR TITLE
Change Side nav default statues to opened

### PR DESCRIPTION
**Pull request by philiphaddad97**
- **Issue**
I found it misleading that the side nav default status is closed while there are a lot of functionalities to use within it.

- **Note**
I'm not a frontend expert but I found a way to modify it =D.

### CODE REVIEW

**Comment by stevermeister** [comment]
@philiphaddad97 thank you for your contribution! 

I only think that it might be better to make it more responsive and for desktops to show on the right always and make it a sidenav for mobile. What do you think?

**Comment by stevermeister** [comment]
also, I see an issue with mobile now - it hides the main screen that should be first, I suppose

**Comment by philiphaddad97** [comment]
Yeah, that's a good point!

I'll see how can I do that.
The side nav should be opened by default for desktop and closed for mobile, is it ok?

**Comment by stevermeister** [comment]
> The side nav should be opened by default for desktop and closed for mobile, is it ok

yes, based on previous feedback, I see it as the best UX.

**Comment by philiphaddad97** [comment]
@stevermeister Can you check it, please?

**Comment by stevermeister** [comment]
yes, that's it!

**Pull request merged**
